apiVersion: apps/v1
kind: Deployment
metadata:
  name: beat
  labels:
    app: beat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beat
  template:
    metadata:
      labels:
        app: beat
    spec:
      containers:
      - name: celery-beat
        image: heliostrome/app:v1
        command: ['celery', '--app=core', 'beat', '--loglevel=INFO' ]
        imagePullPolicy: Always 
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: postgres-cm
        env:
        - name: POSTGRES_HOST
          value: "postgres-svc"
        - name: REDIS_HOST
          value: "redis-svc"
        - name: REDIS_PORT
          value: "6379"
