apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: celery-worker
        image: heliostrome/app:v1
        command: ['celery', '--app=core', 'worker', '--loglevel=INFO' ]
        imagePullPolicy: Always 
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: postgres-cm
        env:
        - name: POSTGRES_HOST
          value: "postgres-svc"
        - name: REDIS_HOST
          value: "redis-svc"
        - name: REDIS_PORT
          value: "6379"
