apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower
  labels:
    app: flower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flower
  template:
    metadata:
      labels:
        app: flower
    spec:
      containers:
      - name: flower
        image: heliostrome/app:v1
        imagePullPolicy: Always 
        command: ['celery','--app=core', 'flower', '--loglevel=INFO', '--address=0.0.0.0']
        ports:
        - containerPort: 5555
        envFrom:
        - configMapRef:
            name: postgres-cm
        env:
        - name: POSTGRES_HOST
          value: "postgres-svc"
        - name: REDIS_HOST
          value: "redis-svc"
        - name: REDIS_PORT
          value: "6379"
        resources:
          limits:
            cpu: 100m
