apiVersion: v1
kind: Service
metadata:
  name: redis-svc
spec:
  selector:
    pod: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc-node
spec:
  selector:
    pod: redis
  type: NodePort 
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
